services:
  - name: redis
    plan: free
    region: oregon
    type: redis
    ipAllowList: []

  - name: backend
    repo: https://github.com/ShivamH1/payout-system.git
    branch: main
    region: oregon
    type: web
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app.onrender.com"
      - key: DB_ENGINE
        value: "postgresql"

  - name: worker
    repo: https://github.com/ShivamH1/payout-system.git
    branch: main
    region: oregon
    type: worker
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: celery -A config worker -l info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: "postgresql"

  - name: beat
    repo: https://github.com/ShivamH1/payout-system.git
    branch: main
    region: oregon
    type: cron
    runtime: python
    schedule: "*/5 * * * *"
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: "postgresql"

databases:
  - name: postgres
    plan: free
    region: oregon